### ISSUE TITLE
Enhance the Makefile

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-beetle#71]
First of all, thank you to the CM-Honeybee maintainers 🙏 
* Ref. [Makefile in the CM-Honeybee repo](https://github.com/cloud-barista/cm-honeybee/blob/main/Makefile)

**What would you like to be enhanced**
: Makefile

**Why is this needed**
: The Makefile in CM-Honeybee includes useful tools for contributing, such as lint, race, dependency, and so on.
: Also, the mechanisms and descriptions are great!

**Proposed solution**
: Review the CM-Honeybee's Makefile and select some of the tools needed.
: Apply the selected tools to CM-Beetle's Makefile.

**Comment by ish-hcc** [comment]
Updated Honeybee Makefile Link : https://github.com/cloud-barista/cm-honeybee/blob/main/agent/Makefile
